<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM5jus3x\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM5jus3x/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerM5jus3x.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerM5jus3x\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerM5jus3x\appProdProjectContainer(array(
    'container.build_hash' => 'M5jus3x',
    'container.build_id' => '19c4ac05',
    'container.build_time' => 1539946073,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM5jus3x');
